
[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = esp32-s3-devkitc-1-n16r8
monitor_speed = 115200
lib_ldf_mode = deep+
board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_opi
build_flags = 
	-DBOARD_HAS_PSRAM
	-std=gnu++2a
	-DCORE_DEBUG_LEVEL=0
	-IC:/Users/user/.platformio/packages/framework-arduinoespressif32/libraries/Network/src
	-IC:/Users/user/.platformio/packages/framework-arduinoespressif32/libraries/FS/src
lib_deps = 
	bblanchon/ArduinoJson@7.4.3
	olikraus/U8g2@2.36.18
	https://github.com/schreibfaul1/ESP32-audioI2S.git
